[workspace]
authors = ["owen-m1ller <omiller@ucsd.edu>"]
channels = ["conda-forge"]
name = "ot-preconditioning"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pot = ">=0.9.6.post1,<0.10"
matplotlib = ">=3.10.8,<4"
numpy = ">=2.4.1,<3"
ipykernel = ">=7.1.0,<8"
scipy = ">=1.17.0,<2"
pillow = ">=12.1.0,<13"
scikit-learn = ">=1.8.0,<2"
opencv = ">=4.12.0,<5"
